name: Code check

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.0

      - name: Install deps
        run: bun install

      - name: Run lint
        run: bun run lint

      - name: Run format
        run: bun run format

      - name: Run typecheck
        run: bun run typecheck
